# port 5000

services:
  big-xo-server:
    build:
      context: .
    environment:
      NODE_ENV: production

networks:
  default:
    name: ${NETWORK_NAME}
    driver: ${NETWORK_NAME+bridge}
    external: ${NETWORK_NAME+true}
